server:
  port: 8081
spring:
  application:
    name: department-service
  datasource:
    url: jdbc:mysql://localhost:3306/department_service
    username: root
    password: Admin@123
    jpa:
      show-sql: true
      properties:
          hibernate:
            format_sql: true  # Format the SQL for readability


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
