server:
  port: 8082
spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/employee_service
    username: root
    password: Admin@123

    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true  # Format the SQL for readability

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
